config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'recipes#index'

  get 'profile', to: 'pages#profile', as: :username
  get 'collection', to: 'pages#collection'

  get 'filterSweet', to: 'recipes#sweet'
  get 'filterSavory', to: 'recipes#savory'

  resources :recipes do
    resources :ingredients, only: [:new, :create, :destroy]
    resources :steps, only:[:new, :create, :destroy, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_one_attached :photo
  has_many :ingredients, dependent: :destroy
  has_many :steps
  belongs_to :user
  validates :photo, presence: true
  validates :name, presence: true
  validates :category, presence: true
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :registerable
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :registerable
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @ingredient = Ingredient.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    ingredient = Ingredient.new(ingredient_params)
    recipe = Recipe.find(params[:recipe_id])
    ingredient.recipe = recipe
    ingredient.save!
    redirect_to new_recipe_ingredient_path(recipe)
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @recipe = Recipe.find(params["recipe_id"].to_i)
    @ingredient.destroy
    redirect_to new_recipe_ingredient_path(@ingredient.recipe)
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:description, :dose, :unit)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  def profile
    @user = current_user

    # @userRecipes =  Recipe.where("user_id == #{current_user}" )
    #  @userRecipe.each do |recipe|
    #     @userPublishedRecipes << recipe if recipe.publish == true
    #   end

    @userPublishedRecipes = []
    @userUnPublishedRecipes = []


    @user.recipe_ids.each do |recipe_id|
      Recipe.find(recipe_id).publish == true ? @userPublishedRecipes << Recipe.find(recipe_id) : @userUnPublishedRecipes << Recipe.find(recipe_id)
    end
  end

  def collection
    @user = current_user

    @userPublishedRecipes = []
    @userUnPublishedRecipes = []


    @user.recipe_ids.each do |recipe_id|
      Recipe.find(recipe_id).publish == true ? @userPublishedRecipes << Recipe.find(recipe_id) : @userUnPublishedRecipes << Recipe.find(recipe_id)
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @publishedRecipes = []
    if params[:category_type].blank?
      Recipe.all.each do |recipe|
        @publishedRecipes << recipe if recipe.publish == true
      end
    else
      @recipes = Recipe.select { |r| r[:name] == params[:category_type]}
    end
  end

  def show
    set_recipe
    @user = User.find(@recipe.user_id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to new_recipe_ingredient_path(@recipe)
    else
      render :new
    end
  end

  def edit
    set_recipe
    @ingredient = Ingredient.new
    @step = Step.new
  end

  def update
    set_recipe
    @recipe.update(recipe_params)
    redirect_to new_recipe_ingredient_path(@recipe)
  end

  def destroy
    set_recipe
    @recipe.delete
    redirect_to root_path
  end

  def sweet
    @publishedRecipes = []
    Recipe.all.each do |recipe|
      @publishedRecipes << recipe if recipe.publish == true
    end
    @publishedRecipes = Recipe.where(category: "Süß")
  end

  def savory
    @publishedRecipes = []
    Recipe.all.each do |recipe|
      @publishedRecipes << recipe if recipe.publish == true
    end
    @publishedRecipes = Recipe.where(category: "Herzhaft")
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :category, :photo, :quantity, :serving, :publish)
  end

end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def new
    @step = Step.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @step = Step.new(step_params)
    # @step.recipe_id = params["recipe_id"].to_i
    @recipe = Recipe.find(params[:recipe_id])
    @step.recipe = @recipe

    if @step.save
      redirect_to new_recipe_step_path(@recipe)
    else
      render :new
    end
    # @step.save!
    # redirect_to edit_recipe_path(recipe)
  end

  def edit
    @recipe = Recipe.find(params["recipe_id"])
    @step = Step.find(params[:id])
  end


  def update
    @step = Step.find(params[:id])
    @recipe = Recipe.find(params["recipe_id"].to_i)
    @step.update(step_params)
    #@step = Step.new(step_params)
    redirect_to new_recipe_step_path(@recipe)

  end


  def destroy
    @step = Step.find(params[:id])
    @recipe = Recipe.find(params["recipe_id"].to_i)
    @step.destroy
    redirect_to new_recipe_step_path(@recipe)
  end

  private

  def step_params
    params.require(:step).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :show]
  def show
    @user = User.find_by_username(params[:username])
  end

  def update
    @user = current_user
    @user.photo = params["user"]["photo"]
    @user.update(user_params)
    redirect_to edit_user_registration_path(@user)

  end

  def user_params
    @user = current_user
    params.require("user").permit("photo")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredients/new.html.erb
<div class="base-container">
  <div class="row justify-content-md-center">
    <div class="col-lg-6 col-md-8 col-sm-12 justify-content-md-center" style="background-color: white">
      <div class="progress">
        <div class="progress-track"></div>
        <div id="step1" class="progress-step is-complete">
          Rezept Details
        </div>
        <div id="step2" class="progress-step is-complete">
          Zutaten
        </div>
        <div id="step3" class="progress-step">
          Zubereitung
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-md-center" id="form-container">
    <div class="col-lg-6 col-md-8 col-sm-12" style="background-color: white">
      <div class="ingredient-container mb-3">
        <% if @recipe.ingredients.empty? == false %>
        <% @recipe.ingredients.each do |ingredient| %>
        <ul>
          <li>
            <div class="d-flex">
              <%= ingredient.dose %> <%= ingredient.unit %> - <%= ingredient.description %>
              <%= render 'shared/delete_ingredient', recipe: @recipe, ingredient: ingredient %>
            </div>
          </li>
        </ul>
        <% end %>
        <% else %>
        <p> Bitte füge Zutaten zu dem Rezept hinzu.</p>
        <% end %>
      </div>
      <div class="collapsable-form">
        <%= render 'shared/add_ingredient'%>
      </div>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-lg-6 col-md-8 col-sm-12 d-flex justify-content-between" style="background-color: white">
      <%= link_to "Zurück", edit_recipe_path(@recipe), class: "btn-shadow ml-3", id:"back"%>
      <%= link_to "Weiter", new_recipe_step_path(@recipe), class: "btn-shadow ml-3", id: "next"%>
    </div>
  </div>
</div>

app/views/pages/collection.html.erb
<div class="base-container">
  <div class="row justify-content-md-center">
    <div class="col-lg-8 col-md-8 col-sm-12 justify-content-md-center">
      <div class="card card-body d-flex justify-content-center align-items-center flex-row">
        <div class="filter-category" style="font-size: 15px">
          <a href="#published">Rezepte</a>
        </div>
        <div class="filter-category" style="font-size: 15px">
          <a href="#draft">Entwürfe</a>
        </div>
      </div>
      <a id="published">
        <h5 style="text-align: center">Veröffentlichte Rezepte (<%=@userPublishedRecipes.count%>)</h5>
      </a>
      <div class="recipe-card-container">
        <%  @userPublishedRecipes.each do |recipe| %>
        <%= link_to recipe_path(recipe), class: 'go-away-url' do %>
        <div class="recipe-card">
          <div class="recipe-card-img-top">
            <% if recipe.photo.attached? %>
            <%= cl_image_tag recipe.photo.key, crop: :fill, id: "index-recipe" %>
            <% else %>
            <%= cl_image_tag("https://res.cloudinary.com/siggimsiggi/image/upload/v1588505411/Rectangle_ttmqdc.png", id: "index-recipe") %>
            <% end %>
          </div>
          <div class="recipe-card-body">
            <% if recipe.name.length <= 15 %>
            <%= link_to recipe.name, recipe_path(recipe) %>
            <% else %>
            <%= link_to recipe.name[0..15], recipe_path(recipe) %>
            <% end %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-lg-8 col-md-8 col-sm-12 justify-content-md-center">
      <a id="draft">
        <h5 style="text-align: center">Entwürfe (<%=@userUnPublishedRecipes.count%>)</h5>
      </a>
      <div class="recipe-card-container">
        <%  @userUnPublishedRecipes.each do |recipe| %>
        <%= link_to recipe_path(recipe), class: 'go-away-url' do %>
        <div class="recipe-card">
          <div class="recipe-card-img-top">
            <% if recipe.photo.attached? %>
            <%= cl_image_tag recipe.photo.key, crop: :fill, id: "index-recipe" %>
            <% else %>
            <%= cl_image_tag("https://res.cloudinary.com/siggimsiggi/image/upload/v1588505411/Rectangle_ttmqdc.png", id: "index-recipe") %>
            <% end %>
          </div>
          <div class="recipe-card-body">
            <% if recipe.name.length <= 15 %>
            <%= link_to recipe.name, recipe_path(recipe) %>
            <% else %>
            <%= link_to recipe.name[0..15], recipe_path(recipe) %>
            <% end %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="base-container">
  <div class="row justify-content-md-center">
    <div class="col-lg-8 col-md-8 col-sm-12 justify-content-md-center">
      <div class="user-profile-info">
        <div class="profile-pic d-flex justify-content-center">
          <%#= cl_image_url @user.photo.key %>
          <div class="default-img">
            <%=@user.username[0] %>
          </div>
        </div>
        <div class="profile-info">
          <h4 style="margin-bottom: 20px;">
            <%= @user.username %>
          </h4>
          <h5>Veröffentlichte Rezepte (<%=@userPublishedRecipes.count%>) </h5>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-lg-8 col-md-8 col-sm-12 justify-content-md-center">
      <div class="user-recipes">
        <div class="recipe-card-container">
          <%  @userPublishedRecipes.each do |recipe| %>
          <%= link_to recipe_path(recipe), class: 'go-away-url' do %>
          <div class="recipe-card">
            <div class="recipe-card-img-top">
              <% if recipe.photo.attached? %>
              <%= cl_image_tag recipe.photo.key, crop: :fill, id: "index-recipe" %>
              <% else %>
              <%= cl_image_tag("https://res.cloudinary.com/siggimsiggi/image/upload/v1588505411/Rectangle_ttmqdc.png", id: "index-recipe") %>
              <% end %>
            </div>
            <div class="recipe-card-body">
              <% if recipe.name.length <= 22 %>
              <%= link_to recipe.name, recipe_path(recipe) %>
              <% else %>
              <%= link_to recipe.name[0..22], recipe_path(recipe) %>
              <% end %>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/recipes.html.erb
<div class="center-container">

<%= cl_image_tag @user.photo %>

  <h3>Veröffentlichte Rezepte (<%=@userPublishedRecipes.count%>)</h3>
  <div class="recipe-card-container">
    <%  @userPublishedRecipes.each do |recipe| %>
    <%= link_to recipe_path(recipe), class: 'go-away-url' do %>
    <div class="recipe-card">
      <div class="recipe-card-img-top">
        <% if recipe.photo.attached? %>
        <%= cl_image_tag recipe.photo.key, crop: :fill, id: "index-recipe" %>
        <% else %>
        <%= cl_image_tag("https://res.cloudinary.com/siggimsiggi/image/upload/v1588505411/Rectangle_ttmqdc.png", id: "index-recipe") %>
        <% end %>
      </div>
      <div class="recipe-card-body">
        <% if recipe.name.length <= 15 %>
        <%= link_to recipe.name, recipe_path(recipe) %>
        <% else %>
        <%= link_to recipe.name[0..15], recipe_path(recipe) %>
        <% end %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>

  <h3>Entwürfe (<%=@userUnPublishedRecipes.count%>)</h3>

  <div class="recipe-card-container">
    <%  @userUnPublishedRecipes.each do |recipe| %>
    <%= link_to recipe_path(recipe), class: 'go-away-url' do %>
    <div class="recipe-card">
      <div class="recipe-card-img-top">
        <% if recipe.photo.attached? %>
        <%= cl_image_tag recipe.photo.key, crop: :fill, id: "index-recipe" %>
        <% else %>
        <%= cl_image_tag("https://res.cloudinary.com/siggimsiggi/image/upload/v1588505411/Rectangle_ttmqdc.png", id: "index-recipe") %>
        <% end %>
      </div>
      <div class="recipe-card-body">
        <% if recipe.name.length <= 15 %>
        <%= link_to recipe.name, recipe_path(recipe) %>
        <% else %>
        <%= link_to recipe.name[0..15], recipe_path(recipe) %>
        <% end %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="base-container">
 <div class="row justify-content-md-center">
  <div class="col-lg-6 col-md-8 col-sm-12 justify-content-md-center" style="background-color: white">
    <div class="progress">
      <div class="progress-track"></div>
      <div id="step1" class="progress-step is-complete">
        Rezept Details
      </div>
      <div id="step2" class="progress-step">
        Zutaten
      </div>
      <div id="step3" class="progress-step">
        Zubereitung
      </div>
    </div>
  </div>
</div>
<div class="row justify-content-md-center" id="form-container">
  <div class="col-lg-6 col-md-8 col-sm-12" style="background-color: white">
    <div class="recipe-edit">
      <%= simple_form_for (@recipe) do |f| %>
      <div class="details-one d-flex">
        <%= f.input :name %>
        <%= f.input :category, collection: ['Herzhaft', 'Süß'], label:"Kategorie", selected: 2%>
      </div>
      <div class="details-two d-flex">
        <%= f.input :serving, placeholder: 'z.B. 2', label:"Anzahl"%>
        <%= f.input :quantity, collection: ['Portionen', 'Stück'], label:"Einheit", selected: 1%>
      </div>
      <%= f.input :photo, as: :file, label: "Foto hochladen" %>
      <%= f.input :publish, as: :radio_buttons, label:"Veröffentlichen?"%>
    </div>
  </div>
</div>
<div class="row justify-content-md-center">
  <div class="col-lg-6 col-md-8 col-sm-12 d-flex justify-content-between" style="background-color: white">
    <%= link_to "Zurück", recipe_path(@recipe), class: "btn-shadow ml-3",id:"back" %>
    <%= f.submit "Weiter", class: "btn-shadow ml-3", id:"next"%>
    <% end %>
  </div>
</div>
</div>

app/views/recipes/index.html.erb
<div class="base-container">
  <%= render 'shared/filterbar' %>
  <div class="row justify-content-md-center">
    <div class="col-lg-8 col-md-8 col-sm-12 justify-content-md-center">
      <div class="recipe-count">
        <h4>
          Rezepte (<%= @publishedRecipes.count %>)
        </h4>
      </div>
    </div>
  </div>
  <%= render 'shared/index' %>
</div>

app/views/recipes/savory.html.erb
<div class="content-container">
  <%= render 'shared/filterbar' %>
  <div class="recipe-count">
    <h4>
      Herzhafte Rezepte (<%= @publishedRecipes.count %>)
    </h4>
  </div>
  <%= render 'shared/index' %>
</div>

app/views/recipes/show.html.erb
<div class="recipe-base-container">

  <div class="content-container">
    <div class="recipe-show-banner">
      <div class="user-info">
        <span style="font-weight: normal"> von </span>
        <%= link_to @user.username, root_path%>
      </div>
      <% if @recipe.photo.attached? %>
      <div class='card-category' style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=cl_image_path @recipe.photo.key%>)'>
        <% else %>
        <div class='card-category' style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)))'>
          <% end %>
          <div class="d-flex flex-column align-items-center">
            <%= @recipe.name %>
            <div class="btn-category d-flex justify-content-center" style="font-size: 15px">
              <%= @recipe.category %>
            </div>
          </div>
        </div>
      </div>

      <% if current_user.id == @recipe.user_id %>
      <div class="tags d-flex justify-content-between">
        <div class="flex-grow-1">
        </div>
        <%= link_to edit_recipe_path(@recipe) do %>
        <i class="fas fa-pen"></i>
        <% end %>
        <%= link_to recipe_path(@recipe),
        method: :delete,
        data: { confirm: "Bist du sicher?" } do %>
        <i class="fas fa-trash"></i>
        <% end %>
      </div>
      <% else %>
      <div stlye="height: 20px">
      </div>
      <% end %>

      <div class="recipe-container d-flex justify-content-between">
        <div class="row">
          <div class="col-lg-5 col-sm-12">
            <div class="recipe-ingredients">
              <% if @recipe.ingredients.empty? == false %>
              <h3>Zutaten: </h3>
              <div class="d-flex mb-3">
                <p>
                  für <span class="servings" style="font-weight: bolder; font-size: 18px"> <%= @recipe.serving %></span>
                  <%= @recipe.quantity %>
                </p>
                <div class="btn-small" id="plus">
                  <p>+</p>
                </div>
                <div class="btn-small" id="minus">
                  <p>-</p>
                </div>
              </div>
              <% @recipe.ingredients.each do |ingredient| %>
              <ul>
                <li>
                  <span class="amount-ingredient" style="font-weight: bolder"><%= ingredient.dose %></span> <%= ingredient.unit %> - <%= ingredient.description %>  </li>
                </li>
              </ul>
              <% end %>
              <% else %>
              <h3>Zutaten: </h3>
              <span> Bitte füge Zutaten zu dem Rezept hinzu.</span>
              <% end %>
            </div>
          </div>
          <div class="col-lg-7 col-sm-12">

            <div class="description">
              <h3>Zubereitung:</h3>
              <% if @recipe.step_ids.empty? == false %>
              <% count = 0 %>
              <% @recipe.step_ids.each do |step| %>
              <% count += 1 %>
              <div class="step-card"id="step-<%= step %>">
                <div class="d-flex">
                  <div class="step-icon" style="position: relative;">
                    <div class="icon">
                      <%= cl_image_tag("https://res.cloudinary.com/siggimsiggi/image/upload/v1588574765/icon_nkwwtg.png") %>
                    </div>
                    <div class="step-id">
                      <%=count%>
                    </div>
                  </div>
                  <div class="step-content">
                    <%= Step.find(step).content %>
                  </div>
                </div>
                <% end %>
              </div>
              <% else %>
              <p>
                Da fehlt doch etwas - bitte füge eine Beschreibung der Zubereitung hinzu.
              </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/shared/_delete_ingredient.html.erb
<%= link_to ('<p style="margin-bottom: 0;padding-left: 15px; color: #ABAAAA; text-decoration: none; padding-bottom: 8px; ">Löschen</p>').html_safe, recipe_ingredient_path(@recipe, ingredient),
method: :delete,
data: { confirm: "Bist du sicher?" } %>

app/views/shared/_delete_step.html.erb
<%= link_to ('<p style="margin-bottom: 0;padding-left: 15px; color: #ABAAAA; text-decoration: none; padding-bottom: 8px; ">Löschen</p>').html_safe, recipe_step_path(@recipe, step),
method: :delete,
data: { confirm: "Bist du sicher?" } %>

app/views/shared/_filterbar.html.erb
<!-- <div class="base-container"> -->
  <div class="row justify-content-md-center">
    <div class="col-lg-8 col-md-8 col-sm-12 justify-content-md-center">
      <div class="d-flex justify-content-end align-items-center">
        <div class="btn-shadow" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          Filtern
        </div>
        <%= link_to "+", new_recipe_path, class: "btn-shadow" %>
      </div>


      <div class="collapse" id="collapseExample">
        <div class="card card-body d-flex justify-content-center align-items-center flex-row">
          <div class="filter-category" style="font-size: 15px">
            <%= link_to "Süß", filterSweet_path %>
          </div>
          <div class="filter-category" style="font-size: 15px">
            <%= link_to "Herzhaft", filterSavory_path %>
          </div>
          <div class="filter-category" style="font-size: 15px">
            <%= link_to "Alle", root_path %>
          </div>
          <!-- <div class="filter-form">
            <div class="filter">
              <form action="/recipes" method="get">
                <input id="field" type="text" name="category_type" placeholder=" Suche nach Zutaten...">
                <input type="submit" class="search" value="&#xf002">
              </form>
            </div>
          </div> -->
        </div>
      </div>
    </div>
  </div>
  <!-- </div> -->

app/views/shared/_index.html.erb
<div class="row justify-content-md-center">
    <div class="col-lg-8 col-md-8 col-sm-12 justify-content-md-center">
      <div class="recipe-card-container">
        <% @publishedRecipes.each do |recipe| %>
        <%= link_to recipe_path(recipe), class: 'go-away-url' do %>
        <div class="recipe-card">
          <div class="recipe-card-img-top">
            <% if recipe.photo.attached? %>
            <%= cl_image_tag recipe.photo.key, crop: :fill, id: "index-recipe" %>
            <% else %>
            <%= cl_image_tag("https://res.cloudinary.com/siggimsiggi/image/upload/v1588505411/Rectangle_ttmqdc.png", id: "index-recipe") %>
            <% end %>
          </div>
          <div class="recipe-card-body">
            <% if recipe.name.length <= 22 %>
            <%= link_to recipe.name, recipe_path(recipe) %>
            <% else %>
            <%= link_to recipe.name[0..22], recipe_path(recipe) %>
            <% end %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="nav-header">
    <%= link_to 'R.ecipes', root_path %>
  </div>

  <div class="nav-actions">

    <div class="navbar-collapse" >
      <ul class="navbar-nav">

        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://www.xing.com/image/1_d_3_75db428b2_24052682_4/alisa-siegmund-foto.256x256.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <div class="nav-links d-flex flex-column">
              <%= link_to "Profil", username_path %>
              <%= link_to "Rezepte", collection_path%>
              <%= link_to "Settings", edit_user_registration_path %>

            </div>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/steps/new.html.erb
<div class="base-container">
  <div class="row justify-content-md-center">
    <div class="col-lg-6 col-md-8 col-sm-12 justify-content-md-center" style="background-color: white">
      <div class="progress">
        <div class="progress-track"></div>
        <div id="step1" class="progress-step is-complete">
          Rezept Details
        </div>
        <div id="step2" class="progress-step is-complete">
          Zutaten
        </div>
        <div id="step3" class="progress-step is-complete">
          Zubereitung
        </div>
      </div>
    </div>
  </div>

  <div class="row justify-content-md-center" id="form-container">
    <div class="col-lg-6 col-md-8 col-sm-12" style="background-color: white">
      <div class="prep-container">
        <% if !@recipe.step_ids.empty? %>
          <% count = 0 %>
          <% @recipe.step_ids.each do |step| %>
          <% count += 1 %>
          <div class="step-card"id="step-<%= step %>">
            <div class="d-flex">
              <div class="step-icon" style="position: relative;">
                <div class="icon">
                  <%= cl_image_tag("https://res.cloudinary.com/siggimsiggi/image/upload/v1588574765/icon_nkwwtg.png") %>
                </div>
                <div class="step-id">
                  <%=count%>
                </div>
              </div>
              <div class="step-content">
                <%= Step.find(step).content %>
              </div>
            </div>
            <div class="d-flex justify-content-end">
              <%= render 'shared/edit_step', recipe: @recipe, step: step %>
              <%= render 'shared/delete_step', recipe: @recipe, step: step %>
            </div>
          </div>
          <div class="collapse" id="collapseEditStep<%= step %>">
            <div class="card card-body" style="margin-left: 25px; border: 0">
              <%= render 'shared/steps', recipe: @recipe, step: step %>
            </div>
          </div>
          <% end %>
        <% else %>
         <p> Bitte füge Zutaten zu dem Rezept hinzu.</p>
         <% end %>

        <div class="collapsable-form">
          <%= render 'shared/add_step'%>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="col-lg-6 col-md-8 col-sm-12 d-flex justify-content-between" style="background-color: white">
      <%= link_to "Zurück", new_recipe_ingredient_path(@recipe), class: "btn-shadow ml-3", id:"back"%>
      <%= link_to "Fertig", recipe_path(@recipe), class: "btn-shadow ml-3", id:"next"%>
    </div>
  </div>
</div>